version: "3.9"
services:
  db:
    image: ankane/pgvector:v0.5.1
    restart: always
    container_name: spoton_db
    environment:
      POSTGRES_DB: spoton_db
      POSTGRES_USER: spoton_user
      POSTGRES_PASSWORD: spoton_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_spoton_data:/var/lib/postgresql/data

volumes:
  postgres_spoton_data:
